# Site settings
title:          导航
description:    "Hello."
baseurl:        ""
url:            "https://xn--fet810g.xn--rlr66kq0bdb82ag2i8t7cqge3n1g.cn/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Control-and-Engineering
  url:          https://孝陵卫皇家理工大学.cn
  email:        m@njust.edu.cn

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale